#TUTORIAL FOR INTNMF
#Install package from R
library(IntNMF)
library(InterSIM) #to simulate genomic data

#Generate data by using INTERSIM package 
prop <- c(0.20,0.30,0.27,0.23)
effect <- 2.5
sim_data <- InterSIM(n.sample=100,cluster.sample.prop=prop,delta.methyl=effect,
                     delta.expr=effect,delta.protein=effect,p.DMP=0.25,p.DEG=NULL,p.DEP=NULL,
                     do.plot=TRUE, sample.cluster=TRUE, feature.cluster=TRUE)
#n.sample: number of subjects
#prop: proportions of samples in the cluster
#delta.*: cluster mean shift for the data
#p.DMP, p.DEG, p.DEP: proportion of DE
#sigma: covariance structure
#do.plot: create heatmap
#sample.cluster: clustering done in samples
#feature.cluster: clustering done in features
##Separate data into omics
dat1 <- sim_data$dat.methyl
dat2 <- sim_data$dat.expr
dat3 <- sim_data$dat.protein
true.cluster.assignment <- sim_data$clustering.assignment

#All the data needs to be positive + scaling of data
if (!all(dat1>=0)) dat1 <- pmax(dat1 + abs(min(dat1)), .Machine$double.eps)
#check if the values from data are >=0, if not we add these values the sum of the minimum
#absolute value of the data, and then it takes the maximum from this value and an
#epsilon value generated by the machine.
dat1 <- dat1/max(dat1)
#Normalization of the data by using the maximum
if (!all(dat2>=0)) dat2 <- pmax(dat2 + abs(min(dat2)), .Machine$double.eps)
dat2 <- dat2/max(dat2)
if (!all(dat3>=0)) dat3 <- pmax(dat3 + abs(min(dat3)), .Machine$double.eps)
dat3 <- dat3/max(dat3)

#Join data: samples on rows and variables on columns
dat <- list(dat1,dat2,dat3)
fit <- nmf.mnnals(dat=dat, k=length(prop), maxiter = 200, st.count = 20, n.ini = 15,
                  ini.nndsvd = TRUE, seed = TRUE)
ClusterEntropy(ComputedClusters = fit$clusters, TrueClasses = true.cluster.assignment$cluster.id)

#Get optimum number of clusters: nmf.opt.k
opt_k<- nmf.opt.k(dat=dat, n.runs = 5, n.fold = 5, k.range = 2:7, result = TRUE, 
                  make.plot = TRUE, progress = TRUE)

#Make silhouette scores
SilhouettePlot(fit, cluster.col = NULL)

#Consensus matrix plot
ConsensusMatPlot(fit,rowLab = TRUE, colLab = TRUE)
